"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var create_1 = require("./create");
var find_1 = require("./find");
var find_all_1 = require("./find-all");
var update_1 = require("./update");
var personRoutes = (0, express_1.Router)();
personRoutes.post("/", create_1.create);
personRoutes.get('/', find_all_1.findAll);
personRoutes.get('/:id', find_1.find);
personRoutes.put('/', update_1.update);
exports.default = personRoutes;
