"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var create_1 = require("./create");
var find_1 = require("./find");
var find_all_1 = require("./find-all");
var update_1 = require("./update");
var userRoutes = (0, express_1.Router)();
userRoutes.post("/", create_1.create);
userRoutes.get('/', find_all_1.findAll);
userRoutes.get('/:id', find_1.find);
userRoutes.put('/', update_1.update);
exports.default = userRoutes;
