"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var require_auth_1 = require("@/http/middlewares/require-auth");
var express_1 = require("express");
var create_1 = require("./create");
var delete_1 = require("./delete");
var find_1 = require("./find");
var list_1 = require("./list");
var list_all_1 = require("./list-all");
var search_1 = require("./search");
var update_1 = require("./update");
var postRoutes = (0, express_1.Router)();
postRoutes.get('/search', search_1.search);
postRoutes.get('/', list_1.list);
postRoutes.post('/', require_auth_1.requireAuth, create_1.create);
postRoutes.post('/all', require_auth_1.requireAuth, list_all_1.listAll);
postRoutes.get('/:id', require_auth_1.requireAuth, find_1.find);
postRoutes.put('/', require_auth_1.requireAuth, update_1.update);
postRoutes.delete('/:id', require_auth_1.requireAuth, delete_1.deletePost);
exports.default = postRoutes;
