-- CARGA DE CATEGORIA
INSERT INTO CATEGORY (NM_CATEGORY, STATUS) VALUES ('Português', true);
INSERT INTO CATEGORY (NM_CATEGORY, STATUS) VALUES ('Matemática', true);
INSERT INTO CATEGORY (NM_CATEGORY, STATUS) VALUES ('Geografica', true);
INSERT INTO CATEGORY (NM_CATEGORY, STATUS) VALUES ('História', true);


-- CARGA DE STATUS
INSERT INTO POST_STATUS (NM_STATUS, STATUS) VALUES ('Rascunho', true);
INSERT INTO POST_STATUS (NM_STATUS, STATUS) VALUES ('Em avaliação', true);
INSERT INTO POST_STATUS (NM_STATUS, STATUS) VALUES ('Em avaliação', true);


