-- CARGA DE CATEGORIA
INSERT INTO BLOG.CATEGORY (NM_CATEGORY, STATUS) VALUES ('Português', true);
INSERT INTO BLOG.CATEGORY (NM_CATEGORY, STATUS) VALUES ('Matemática', true);
INSERT INTO BLOG.CATEGORY (NM_CATEGORY, STATUS) VALUES ('Geografica', true);
INSERT INTO BLOG.CATEGORY (NM_CATEGORY, STATUS) VALUES ('História', true);


-- CARGA DE STATUS
INSERT INTO BLOG.POST_STATUS (NM_STATUS, STATUS) VALUES ('Rascunho', true);
INSERT INTO BLOG.POST_STATUS (NM_STATUS, STATUS) VALUES ('Em avaliação', true);
INSERT INTO BLOG.POST_STATUS (NM_STATUS, STATUS) VALUES ('Aprovado', true);
INSERT INTO BLOG.POST_STATUS (NM_STATUS, STATUS) VALUES ('Reprovado', true);
INSERT INTO BLOG.POST_STATUS (NM_STATUS, STATUS) VALUES ('Ocultado', true);
INSERT INTO BLOG.POST_STATUS (NM_STATUS, STATUS) VALUES ('Excluído', true);
INSERT INTO BLOG.POST_STATUS (NM_STATUS, STATUS) VALUES ('Publicado', true);


-- CARGA DE PESSOA
INSERT INTO BLOG.PERSON (NAME, CPF, BIRTH, EMAIL, STATUS) VALUES ('João', '000.000.000-00', '1990-01-01', 'joao@gmail.com', true);
INSERT INTO BLOG.PERSON (NAME, CPF, BIRTH, EMAIL, STATUS) VALUES ('Maria', '000.000.000-01', '1980-01-01', 'maria@gmail.com', true);